### ISSUE TITLE
Cannot save form without filling in a hidden nonessential field

### ISSUE THREAD

**Issue by rdmolony** [mainstreamrp-dev/support#18]
Will be resolved on completion of:

- https://github.com/mainstreamrp-dev/support/issues/30
- https://github.com/mainstreamrp-dev/support/issues/33

See description below ...

**Comment by rdmolony** [comment]
@r-molins-mrp would you mind editing above with corrections?

**Comment by r-molins-mrp** [comment]
In the Admin view of any station (e.g. http://ieazneureact/admin/stationmanager/station/38/change/), the 'Idreference station' field under 'Additional' is currently mandatory. This results in any edit made in the Admin Station page not being saved unless that field is filled. However if 'Additional' section is hidden you don't see the  warning, so the user doesn't understand why his changes are not saved:
![image](https://user-images.githubusercontent.com/93541751/139709251-785f5eaa-2862-4590-9e05-436f60c2dcc3.png)

You would have to 'Show' the 'Additional' section for the warning message to pop up:
![image](https://user-images.githubusercontent.com/93541751/139709355-d4df22f5-7685-44c4-819e-56f5dcac750f.png)

Suggested fix: the 'Iddreference station' should not be mandatory to fill, it should be optional as the others fields in this category.

**Comment by rdmolony** [comment]
Looking like a big issue ...

> I was editing Florida station CH019-01.  After updating some logs and uploading maintenance reports, I realized that it is not possible to save the changes. Everything done was not saved.

**Comment by rdmolony** [comment]
**Workaround**

> Expand all of the sections and check that there are no red fields highlighted. I suspect that this could be due to the reference station field in the additional section being incomplete.

**Comment by r-molins-mrp** [comment]
I would propose to simply not make the 'Iddreference station' field mandatory - I don't think it's used for anything required in the code afterwards, this was one of the change that happened when our contracto changed the code earlier this year.

**Comment by rdmolony** [comment]
Still getting to grips with Django

Looks like `models.py` defines this field as not mandatory as `null=True`, however, perhaps the fact that it is a `ForeignKey` overrides this as I believe this is used to link `Station` to other tables

```python
class Station(models.Model):
    idreference_station = models.ForeignKey('self', null=True, blank=True, db_column='idReference_Station',
                                                verbose_name='Reference Station', on_delete=CASCADE)
```

**Comment by rdmolony** [comment]
Alternatively we could either uncollapse `Additional` or we could move `idreference_station` into the **Required** section to make it more visible for the user on save

```python
class StationAdmin(admin.ModelAdmin):
    form = StationForm
    save_on_top = True

    fieldsets = (
        ('Required', {
            'classes': ('wide',),
            'fields': ('name',
                       'idproject',
                       'idstationtype',
                       'idstationstatus',
                       ('latitude', 'longitude',),
                       ('townland', 'state'),
                       )
        }),

        ('Installation and Maintenance', {
            'classes': ('collapse', 'wide'),
            'fields': (('commission_date', 'has_commissioning_forms'),
                       'commission_report_url',
                       'oriented_to_true_north',
                       'has_aviation_light',
                       'has_anabat',
                       'to_be_insured_by_mrp',
                       'idinstaller',
                       ('cost', 'idcurrency',),
                       'insured_value',

                       'next_maintenance_date',
                       ('last_maintenance_date', 'idlast_maintenance_contractor'),
                       'last_maintenance_report_url',

                       'landowner_name',
                       'landowner_phone',
                       'landowner_address',
                       'decommission_date'
                       ),
        }),

        ('Additional', {
            'classes': ('collapse', 'wide'),
            'fields': ('idowner',
                       'height',
                       'base_height',
                       'elevation',
                       'idreference_station',
                       'idmanufacturer',
                       'firmware_version',
                       'notes',
                       ('utm_x', 'utm_y', 'idutmzone'),
                       ),
        }),

    )
```

**Comment by rdmolony** [comment]
for those with the requisite permissions - https://github.com/mainstreamrp-dev/StationManager

**Comment by rdmolony** [comment]
it makes sense that `ForeignKey` fields are mandatory as whenever a station is deleted from the db it will then also be deleted from the related tables when the `on_delete` is `CASCADE` like `models.ForeignKey('self', ... on_delete=CASCADE)` - - https://riptutorial.com/django/example/30649/foreignkey

**Comment by rdmolony** [comment]
Setting `ForeignKey` to self instead of to another model class like `Project` (which itself links to all stations) seems weird to me.

The [`Django` docs](https://docs.djangoproject.com/en/3.2/ref/models/fields/) define this as:

> To create a recursive relationship – an object that has a many-to-one relationship with itself – use models.ForeignKey('self', on_delete=models.CASCADE).

**Comment by rdmolony** [comment]
This applies to multiple form pages so I'm making separate sub-issues for each

**Comment by rdmolony** [comment]
[stackabuse](https://stackabuse.com/recursive-model-relationships-in-django/) illustrate the use of a recursive relationship in an `Employee` model to link employees to their managers, who are also employees.

```python
from django.db import models

class Employee(models.Model):
    STANDARD = 'STD'
    MANAGER = 'MGR'
    SR_MANAGER = 'SRMGR'
    PRESIDENT = 'PRES'

    EMPLOYEE_TYPES = (
        (STANDARD, 'base employee'),
        (MANAGER, 'manager'),
        (SR_MANAGER, 'senior manager'),
        (PRESIDENT, 'president')
    )

    role = models.CharField(max_length=25, choices=EMPLOYEE_TYPES)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    manager = models.ForeignKey('self', null=True, related_name='employee')
```

**Comment by rdmolony** [comment]
Perhaps the database thinks that this field is required and we just needs a database migration to update this spec

**Comment by rdmolony** [comment]
Deleting ...

```python
idreference_station = models.ForeignKey('self', null=True, blank=True, db_column='idReference_Station',
                                            verbose_name='Reference Station', on_delete=CASCADE)
```

... from `Station` in `models.py` and migrating the database to the new fields revealed the problem.  Even after removal of this field the admin page still displayed it and required it to be entered.  Puzzling.  

It turns out that  `StationForm` in `admin.py` also references this field ...

```python
idreference_station = ModelChoiceField(queryset=Station.objects
                                           .select_related('idproject__idcountry',
                                                           'idstationstatus',
                                                           'idowner'))
```

... and overrides the original field definition in `Station` in `models.py`.  By default it seems `ModelChoiceField` requires user input or `required=True` .  Adding the argument `required=False` enables the field to once again be an optional field.  

**Note:** All mandatory arguments appear in bold!
